package com.mcms.codegen.generator;

import com.mcms.codegen.model.StateMachineDef;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;

/**
 * Generates domain event record classes from StateMachineDef.
 * Uses string templates instead of JavaPoet because JavaPoet 1.13.0
 * does not natively support Java records.
 *
 * Each event is a simple record with (Long entityId, Instant timestamp).
 */
public class EventClassGenerator {

    private static final Logger logger = LoggerFactory.getLogger(EventClassGenerator.class);

    private final Path outputDirectory;
    private static final String EVENTS_PACKAGE = "com.mcms.events";

    public EventClassGenerator(Path outputDirectory) {
        this.outputDirectory = outputDirectory;
    }

    public void generate(StateMachineDef sm) throws IOException {
        List<String> eventNames = sm.allEventNames();
        logger.info("Generating {} event classes for {} state machine", eventNames.size(), sm.modelName());

        Path packageDir = outputDirectory.resolve(EVENTS_PACKAGE.replace('.', '/'));
        Files.createDirectories(packageDir);

        for (String eventName : eventNames) {
            generateEventRecord(eventName, sm.modelName(), packageDir);
        }
    }

    private void generateEventRecord(String eventName, String modelName, Path packageDir) throws IOException {
        String content = """
            // GENERATED by MCMS Code Generator - DO NOT EDIT
            // Source: mcms-states.dsl
            // Generated: %s
            package %s;

            import java.time.Instant;

            /**
             * Domain event emitted during %s state machine transitions.
             *
             * @param entityId The ID of the %s entity that triggered this event
             * @param timestamp When the event occurred
             */
            public record %s(Long entityId, Instant timestamp) {

                /**
                 * Convenience factory method.
                 */
                public static %s now(Long entityId) {
                    return new %s(entityId, Instant.now());
                }
            }
            """.formatted(
                Instant.now().toString(),
                EVENTS_PACKAGE,
                modelName,
                modelName,
                eventName,
                eventName,
                eventName
            );

        Path filePath = packageDir.resolve(eventName + ".java");
        Files.writeString(filePath, content);
        logger.info("Generated: {}/{}.java", EVENTS_PACKAGE.replace('.', '/'), eventName);
    }
}
