package com.mcms.codegen.generator;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;

/**
 * Generates exception classes used by the generated state machine code.
 * Uses string templates because these are simple utility classes.
 */
public class ExceptionClassGenerator {

    private static final Logger logger = LoggerFactory.getLogger(ExceptionClassGenerator.class);

    private final Path outputDirectory;
    private static final String PACKAGE_NAME = "com.mcms.statemachine";

    public ExceptionClassGenerator(Path outputDirectory) {
        this.outputDirectory = outputDirectory;
    }

    public void generate() throws IOException {
        Path packageDir = outputDirectory.resolve(PACKAGE_NAME.replace('.', '/'));
        Files.createDirectories(packageDir);

        generateInvalidStateTransitionException(packageDir);
        generateGuardFailedException(packageDir);
    }

    private void generateInvalidStateTransitionException(Path packageDir) throws IOException {
        String content = """
            // GENERATED by MCMS Code Generator - DO NOT EDIT
            // Generated: %s
            package %s;

            /**
             * Thrown when a state machine transition is attempted from an invalid state.
             */
            public class InvalidStateTransitionException extends RuntimeException {

                private final String currentState;
                private final String expectedState;

                public InvalidStateTransitionException(String currentState, String expectedState) {
                    super(String.format(
                        "Invalid state transition: current state is %%s, expected %%s",
                        currentState, expectedState));
                    this.currentState = currentState;
                    this.expectedState = expectedState;
                }

                public String getCurrentState() {
                    return currentState;
                }

                public String getExpectedState() {
                    return expectedState;
                }
            }
            """.formatted(Instant.now().toString(), PACKAGE_NAME);

        Files.writeString(packageDir.resolve("InvalidStateTransitionException.java"), content);
        logger.info("Generated: {}/InvalidStateTransitionException.java", PACKAGE_NAME.replace('.', '/'));
    }

    private void generateGuardFailedException(Path packageDir) throws IOException {
        String content = """
            // GENERATED by MCMS Code Generator - DO NOT EDIT
            // Generated: %s
            package %s;

            /**
             * Thrown when a state machine guard condition fails, preventing a transition.
             */
            public class GuardFailedException extends RuntimeException {

                private final String modelName;
                private final String fromState;
                private final String toState;
                private final String guardExpression;

                public GuardFailedException(String modelName, String fromState,
                                            String toState, String guardExpression) {
                    super(String.format(
                        "Guard failed for %%s transition %%s -> %%s: %%s",
                        modelName, fromState, toState, guardExpression));
                    this.modelName = modelName;
                    this.fromState = fromState;
                    this.toState = toState;
                    this.guardExpression = guardExpression;
                }

                public String getModelName() {
                    return modelName;
                }

                public String getFromState() {
                    return fromState;
                }

                public String getToState() {
                    return toState;
                }

                public String getGuardExpression() {
                    return guardExpression;
                }
            }
            """.formatted(Instant.now().toString(), PACKAGE_NAME);

        Files.writeString(packageDir.resolve("GuardFailedException.java"), content);
        logger.info("Generated: {}/GuardFailedException.java", PACKAGE_NAME.replace('.', '/'));
    }
}
