package com.mcms.codegen.generator;

import com.mcms.codegen.model.StateMachineDef;
import com.mcms.codegen.model.TransitionDef;
import com.squareup.javapoet.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates state machine classes from StateMachineDef using JavaPoet.
 *
 * Pattern (from AGENT_MEMORIES.md):
 *   1. logger.debug("TRANSITION: FROM -> TO | trigger=eventName")
 *   2. assertState(EXPECTED_FROM_STATE) // MANDATORY
 *   3. check guard (if present)
 *   4. set new state
 *   5. emit events
 *   6. execute actions
 */
public class StateMachineGenerator {

    private static final Logger logger = LoggerFactory.getLogger(StateMachineGenerator.class);

    private final Path outputDirectory;
    private static final String PACKAGE_NAME = "com.mcms.statemachine";
    private static final String ENTITY_PACKAGE = "com.mcms.domain";
    private static final String ENUM_PACKAGE = "com.mcms.domain.enumeration";
    private static final String EVENTS_PACKAGE = "com.mcms.events";

    public StateMachineGenerator(Path outputDirectory) {
        this.outputDirectory = outputDirectory;
    }

    public void generate(StateMachineDef sm) throws IOException {
        String className = sm.modelName() + "StateMachine";
        logger.info("Generating state machine: {}.{}", PACKAGE_NAME, className);

        ClassName entityClass = ClassName.get(ENTITY_PACKAGE, sm.modelName());
        ClassName phaseEnum = ClassName.get(ENUM_PACKAGE, "PhaseName");
        ClassName loggerClass = ClassName.get("org.slf4j", "Logger");
        ClassName loggerFactoryClass = ClassName.get("org.slf4j", "LoggerFactory");

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("// GENERATED by MCMS Code Generator - DO NOT EDIT\n")
            .addJavadoc("// Source: mcms-states.dsl\n")
            .addJavadoc("// Generated: $L\n", Instant.now().toString())
            .addJavadoc("//\n")
            .addJavadoc("// State machine for $L entity with $L states and $L transitions.\n",
                sm.modelName(), sm.states().size(), sm.transitions().size());

        // Field: logger
        classBuilder.addField(FieldSpec.builder(loggerClass, "logger", Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .initializer("$T.getLogger($L.class)", loggerFactoryClass, className)
            .build());

        // Field: wrapped entity
        String entityFieldName = lowerFirst(sm.modelName());
        classBuilder.addField(FieldSpec.builder(entityClass, entityFieldName, Modifier.PRIVATE)
            .build());

        // Field: emitted events list
        ClassName listClass = ClassName.get("java.util", "List");
        ClassName arrayListClass = ClassName.get("java.util", "ArrayList");
        TypeName eventListType = ParameterizedTypeName.get(listClass, ClassName.get("java.lang", "Object"));
        classBuilder.addField(FieldSpec.builder(eventListType, "emittedEvents", Modifier.PRIVATE, Modifier.FINAL)
            .initializer("new $T<>()", arrayListClass)
            .build());

        // Constructor
        classBuilder.addMethod(MethodSpec.constructorBuilder()
            .addModifiers(Modifier.PUBLIC)
            .addParameter(entityClass, entityFieldName)
            .addStatement("this.$L = $L", entityFieldName, entityFieldName)
            .build());

        // Transition methods
        for (TransitionDef t : sm.transitions()) {
            classBuilder.addMethod(generateTransitionMethod(sm, t, entityFieldName, phaseEnum));
        }

        // assertState helper
        classBuilder.addMethod(generateAssertStateMethod(sm, entityFieldName, phaseEnum));

        // getCurrentState
        classBuilder.addMethod(MethodSpec.methodBuilder("getCurrentState")
            .addModifiers(Modifier.PUBLIC)
            .returns(phaseEnum)
            .addStatement("return $L.getCurrentPhase()", entityFieldName)
            .build());

        // getEmittedEvents
        classBuilder.addMethod(MethodSpec.methodBuilder("getEmittedEvents")
            .addModifiers(Modifier.PUBLIC)
            .returns(ParameterizedTypeName.get(
                ClassName.get("java.util", "List"),
                ClassName.get("java.lang", "Object")))
            .addStatement("return $T.unmodifiableList(emittedEvents)",
                ClassName.get("java.util", "Collections"))
            .build());

        // clearEmittedEvents
        classBuilder.addMethod(MethodSpec.methodBuilder("clearEmittedEvents")
            .addModifiers(Modifier.PUBLIC)
            .addStatement("emittedEvents.clear()")
            .build());

        // getEntity
        classBuilder.addMethod(MethodSpec.methodBuilder("get" + sm.modelName())
            .addModifiers(Modifier.PUBLIC)
            .returns(entityClass)
            .addStatement("return $L", entityFieldName)
            .build());

        // Guard stubs (simple boolean guards only)
        for (String guard : sm.simpleGuardNames()) {
            classBuilder.addMethod(MethodSpec.methodBuilder(guard)
                .addModifiers(Modifier.PROTECTED)
                .returns(boolean.class)
                .addJavadoc("Guard stub - override to implement real logic.\n")
                .addStatement("return true")
                .build());
        }

        // Action stubs
        for (String action : sm.allActionNames()) {
            classBuilder.addMethod(MethodSpec.methodBuilder(action)
                .addModifiers(Modifier.PROTECTED)
                .addJavadoc("Action stub - override to implement real logic.\n")
                .addStatement("logger.debug(\"Action: $L()\")", action)
                .build());
        }

        JavaFile javaFile = JavaFile.builder(PACKAGE_NAME, classBuilder.build())
            .skipJavaLangImports(true)
            .indent("    ")
            .build();

        javaFile.writeTo(outputDirectory);
        logger.info("Generated: {}/{}.java", PACKAGE_NAME.replace('.', '/'), className);
    }

    private MethodSpec generateTransitionMethod(StateMachineDef sm, TransitionDef t,
                                                 String entityFieldName, ClassName phaseEnum) {
        MethodSpec.Builder method = MethodSpec.methodBuilder(t.trigger())
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Transition: $L -> $L\n", t.fromState(), t.toState());

        if (t.hasGuard()) {
            method.addJavadoc("Guard: $L\n", t.guard().get());
        }

        // Add parameters
        for (String param : t.parameters()) {
            method.addParameter(Object.class, param);
        }

        // 1. Log
        method.addStatement(
            "logger.debug(\"$L[id={}] TRANSITION: $L -> $L | trigger=$L\", $L.getId())",
            sm.modelName(), t.fromState(), t.toState(), t.trigger(), entityFieldName
        );

        // 2. Assert state (MANDATORY)
        method.addStatement("assertState($T.$L)", phaseEnum, t.fromState());

        // 3. Guard check (if present)
        if (t.hasGuard()) {
            String guardExpr = t.guard().get();
            if (t.hasSimpleGuard()) {
                // Simple boolean guard -> method call
                method.beginControlFlow("if (!$L())", guardExpr);
            } else {
                // Complex expression guard -> inline check with method stubs
                // Replace identifier references with method calls for known guards
                method.beginControlFlow("if (!guardCheck_$L())", t.trigger());
            }
            method.addStatement(
                "throw new $T(\"$L\", \"$L\", \"$L\", \"$L\")",
                ClassName.get(PACKAGE_NAME, "GuardFailedException"),
                sm.modelName(), t.fromState(), t.toState(), guardExpr
            );
            method.endControlFlow();
        }

        // 4. Set new state
        method.addStatement("$L.setCurrentPhase($T.$L)", entityFieldName, phaseEnum, t.toState());

        // 5. Emit events
        for (String event : t.emits()) {
            method.addStatement(
                "emittedEvents.add(new $T($L.getId(), $T.now()))",
                ClassName.get(EVENTS_PACKAGE, event),
                entityFieldName,
                Instant.class
            );
        }

        // 6. Execute actions
        for (String action : t.actions()) {
            method.addStatement("$L()", action);
        }

        return method.build();
    }

    private MethodSpec generateAssertStateMethod(StateMachineDef sm, String entityFieldName,
                                                  ClassName phaseEnum) {
        return MethodSpec.methodBuilder("assertState")
            .addModifiers(Modifier.PRIVATE)
            .addParameter(phaseEnum, "expected")
            .addJavadoc("Validates that the entity is in the expected state before transitioning.\n")
            .beginControlFlow("if ($L.getCurrentPhase() != expected)", entityFieldName)
            .addStatement(
                "throw new $T($L.getCurrentPhase().name(), expected.name())",
                ClassName.get(PACKAGE_NAME, "InvalidStateTransitionException"),
                entityFieldName
            )
            .endControlFlow()
            .build();
    }

    /** Generate guard check methods for complex guard expressions. */
    public void generateComplexGuardStubs(StateMachineDef sm, TypeSpec.Builder classBuilder) {
        for (TransitionDef t : sm.transitions()) {
            if (t.hasGuard() && !t.hasSimpleGuard()) {
                classBuilder.addMethod(MethodSpec.methodBuilder("guardCheck_" + t.trigger())
                    .addModifiers(Modifier.PROTECTED)
                    .returns(boolean.class)
                    .addJavadoc("Complex guard stub for transition $L -> $L.\n", t.fromState(), t.toState())
                    .addJavadoc("Original expression: $L\n", t.guard().get())
                    .addJavadoc("TODO: Implement actual guard logic.\n")
                    .addStatement("return true")
                    .build());
            }
        }
    }

    private static String lowerFirst(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toLowerCase(s.charAt(0)) + s.substring(1);
    }
}
