package com.mcms.codegen.generator;

import com.mcms.codegen.model.StateMachineDef;
import com.mcms.codegen.model.TransitionDef;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates JUnit 5 test classes for state machines.
 * Uses string templates because the test structure includes @Nested, @DisplayName,
 * and AssertJ assertions which are easier to template than to build with JavaPoet.
 */
public class TestGenerator {

    private static final Logger logger = LoggerFactory.getLogger(TestGenerator.class);

    private final Path outputDirectory;
    private static final String TEST_PACKAGE = "com.mcms.statemachine";

    public TestGenerator(Path outputDirectory) {
        this.outputDirectory = outputDirectory;
    }

    public void generate(StateMachineDef sm) throws IOException {
        String testClassName = sm.modelName() + "StateMachineTest";
        logger.info("Generating test class: {}.{}", TEST_PACKAGE, testClassName);

        Path packageDir = outputDirectory.resolve(TEST_PACKAGE.replace('.', '/'));
        Files.createDirectories(packageDir);

        StringBuilder sb = new StringBuilder();
        sb.append(generateHeader(sm, testClassName));
        sb.append(generateImports(sm));
        sb.append(generateClassOpen(sm, testClassName));
        sb.append(generateHelperMethods(sm));

        // Generate nested test class for each transition
        for (TransitionDef t : sm.transitions()) {
            sb.append(generateTransitionTests(sm, t));
        }

        // Generate invalid transition tests
        sb.append(generateInvalidTransitionTests(sm));

        // Generate full lifecycle test
        sb.append(generateFullLifecycleTest(sm));

        sb.append("}\n");

        Path filePath = packageDir.resolve(testClassName + ".java");
        Files.writeString(filePath, sb.toString());
        logger.info("Generated: {}/{}.java", TEST_PACKAGE.replace('.', '/'), testClassName);
    }

    private String generateHeader(StateMachineDef sm, String testClassName) {
        return """
            // GENERATED by MCMS Code Generator - DO NOT EDIT
            // Source: mcms-states.dsl
            // Generated: %s
            """.formatted(Instant.now().toString());
    }

    private String generateImports(StateMachineDef sm) {
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(TEST_PACKAGE).append(";\n\n");
        sb.append("import com.mcms.domain.Batch;\n");
        sb.append("import com.mcms.domain.enumeration.PhaseName;\n");

        for (String event : sm.allEventNames()) {
            sb.append("import com.mcms.events.").append(event).append(";\n");
        }

        sb.append("\n");
        sb.append("import org.junit.jupiter.api.DisplayName;\n");
        sb.append("import org.junit.jupiter.api.Nested;\n");
        sb.append("import org.junit.jupiter.api.Test;\n");
        sb.append("\n");
        sb.append("import java.time.LocalDate;\n");
        sb.append("\n");
        sb.append("import static org.assertj.core.api.Assertions.*;\n");
        sb.append("\n");
        return sb.toString();
    }

    private String generateClassOpen(StateMachineDef sm, String testClassName) {
        return """
            @DisplayName("%s State Machine")
            class %s {

            """.formatted(sm.modelName(), testClassName);
    }

    private String generateHelperMethods(StateMachineDef sm) {
        return """
                private Batch createBatchInState(PhaseName state) {
                    Batch batch = new Batch();
                    batch.setId(1L);
                    batch.setBatchCode("TEST-001");
                    batch.setCurrentPhase(state);
                    batch.setStartDate(LocalDate.now());
                    batch.setIsActive(true);
                    batch.setFlushNumber(1);
                    batch.setMaxFlushes(3);
                    return batch;
                }

            """;
    }

    private String generateTransitionTests(StateMachineDef sm, TransitionDef t) {
        String nestedClassName = capitalize(t.trigger()) + "Test";
        StringBuilder sb = new StringBuilder();

        sb.append("    @Nested\n");
        sb.append("    @DisplayName(\"").append(t.fromState()).append(" -> ")
            .append(t.toState()).append(" on ").append(t.trigger()).append("\")\n");
        sb.append("    class ").append(nestedClassName).append(" {\n\n");

        // Happy path test
        sb.append("        @Test\n");
        sb.append("        @DisplayName(\"should transition to ").append(t.toState()).append("\")\n");
        sb.append("        void shouldTransition() {\n");
        sb.append("            Batch batch = createBatchInState(PhaseName.").append(t.fromState()).append(");\n");
        sb.append("            BatchStateMachine sm = new BatchStateMachine(batch);\n\n");
        sb.append("            sm.").append(t.trigger()).append("();\n\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.").append(t.toState()).append(");\n");

        if (!t.emits().isEmpty()) {
            sb.append("            assertThat(sm.getEmittedEvents()).hasSize(").append(t.emits().size()).append(");\n");
            sb.append("            assertThat(sm.getEmittedEvents().get(0)).isInstanceOf(")
                .append(t.emits().get(0)).append(".class);\n");
        }

        sb.append("        }\n\n");

        // Wrong state rejection test
        String wrongState = findWrongState(sm, t);
        sb.append("        @Test\n");
        sb.append("        @DisplayName(\"should reject transition from wrong state\")\n");
        sb.append("        void shouldRejectWrongState() {\n");
        sb.append("            Batch batch = createBatchInState(PhaseName.").append(wrongState).append(");\n");
        sb.append("            BatchStateMachine sm = new BatchStateMachine(batch);\n\n");
        sb.append("            assertThatThrownBy(() -> sm.").append(t.trigger()).append("())\n");
        sb.append("                .isInstanceOf(InvalidStateTransitionException.class);\n");
        sb.append("        }\n\n");

        // Guard failure test (if guard is simple boolean)
        if (t.hasSimpleGuard()) {
            sb.append("        @Test\n");
            sb.append("        @DisplayName(\"should reject when guard ").append(t.guard().get()).append(" fails\")\n");
            sb.append("        void shouldRejectWhenGuardFails() {\n");
            sb.append("            Batch batch = createBatchInState(PhaseName.").append(t.fromState()).append(");\n");
            sb.append("            // Override guard to return false\n");
            sb.append("            BatchStateMachine sm = new BatchStateMachine(batch) {\n");
            sb.append("                @Override protected boolean ").append(t.guard().get()).append("() { return false; }\n");
            sb.append("            };\n\n");
            sb.append("            assertThatThrownBy(() -> sm.").append(t.trigger()).append("())\n");
            sb.append("                .isInstanceOf(GuardFailedException.class);\n");
            sb.append("        }\n\n");
        }

        sb.append("    }\n\n");
        return sb.toString();
    }

    private String generateInvalidTransitionTests(StateMachineDef sm) {
        StringBuilder sb = new StringBuilder();
        sb.append("    @Nested\n");
        sb.append("    @DisplayName(\"Invalid transitions - phase skipping prevention\")\n");
        sb.append("    class InvalidTransitionTests {\n\n");

        // Test that INOCULATION can't skip to a late phase
        sb.append("        @Test\n");
        sb.append("        @DisplayName(\"should prevent skipping from INOCULATION to HARVEST\")\n");
        sb.append("        void shouldPreventSkipToHarvest() {\n");
        sb.append("            Batch batch = createBatchInState(PhaseName.INOCULATION);\n");
        sb.append("            BatchStateMachine sm = new BatchStateMachine(batch);\n\n");
        sb.append("            assertThatThrownBy(() -> sm.startHarvest())\n");
        sb.append("                .isInstanceOf(InvalidStateTransitionException.class);\n");
        sb.append("        }\n\n");

        // Test that COMPLETED is terminal
        sb.append("        @Test\n");
        sb.append("        @DisplayName(\"should prevent any transition from COMPLETED\")\n");
        sb.append("        void shouldPreventTransitionFromCompleted() {\n");
        sb.append("            Batch batch = createBatchInState(PhaseName.COMPLETED);\n");
        sb.append("            BatchStateMachine sm = new BatchStateMachine(batch);\n\n");
        sb.append("            assertThatThrownBy(() -> sm.startColonization())\n");
        sb.append("                .isInstanceOf(InvalidStateTransitionException.class);\n");
        sb.append("        }\n\n");

        sb.append("    }\n\n");
        return sb.toString();
    }

    private String generateFullLifecycleTest(StateMachineDef sm) {
        StringBuilder sb = new StringBuilder();
        sb.append("    @Nested\n");
        sb.append("    @DisplayName(\"Full lifecycle\")\n");
        sb.append("    class FullLifecycleTest {\n\n");

        sb.append("        @Test\n");
        sb.append("        @DisplayName(\"should complete full batch lifecycle from INOCULATION to COMPLETED\")\n");
        sb.append("        void shouldCompleteFullLifecycle() {\n");
        sb.append("            Batch batch = createBatchInState(PhaseName.INOCULATION);\n");
        sb.append("            batch.setFlushNumber(3);\n");
        sb.append("            batch.setMaxFlushes(3);\n");
        sb.append("            BatchStateMachine sm = new BatchStateMachine(batch);\n\n");

        // Walk through the straight-line path (no rehydration loop)
        sb.append("            sm.startColonization();\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.EARLY_COLONIZATION);\n\n");
        sb.append("            sm.confirmFullColonization();\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.FULL_COLONIZATION);\n\n");
        sb.append("            sm.startConsolidation();\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.CONSOLIDATION);\n\n");
        sb.append("            sm.triggerFruiting();\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.FRUITING_TRIGGER);\n\n");
        sb.append("            sm.confirmPrimordia();\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.PRIMORDIA);\n\n");
        sb.append("            sm.startFruitingGrowth();\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.FRUITING_BODY_GROWTH);\n\n");
        sb.append("            sm.startHarvest();\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.HARVEST);\n\n");
        sb.append("            sm.endBatch();\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.COMPLETED);\n\n");
        sb.append("            // Verify events were emitted for each transition\n");
        sb.append("            assertThat(sm.getEmittedEvents()).hasSize(8);\n");
        sb.append("        }\n\n");

        sb.append("        @Test\n");
        sb.append("        @DisplayName(\"should support multi-flush harvest cycle\")\n");
        sb.append("        void shouldSupportMultiFlushCycle() {\n");
        sb.append("            Batch batch = createBatchInState(PhaseName.INOCULATION);\n");
        sb.append("            batch.setFlushNumber(1);\n");
        sb.append("            batch.setMaxFlushes(3);\n");
        sb.append("            BatchStateMachine sm = new BatchStateMachine(batch);\n\n");

        sb.append("            // Progress to first harvest\n");
        sb.append("            sm.startColonization();\n");
        sb.append("            sm.confirmFullColonization();\n");
        sb.append("            sm.startConsolidation();\n");
        sb.append("            sm.triggerFruiting();\n");
        sb.append("            sm.confirmPrimordia();\n");
        sb.append("            sm.startFruitingGrowth();\n");
        sb.append("            sm.startHarvest();\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.HARVEST);\n\n");

        sb.append("            // Rehydrate for second flush\n");
        sb.append("            sm.rehydrate();\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.REHYDRATION_PAUSE);\n\n");

        sb.append("            // Restart fruiting\n");
        sb.append("            sm.restartFruiting();\n");
        sb.append("            assertThat(sm.getCurrentState()).isEqualTo(PhaseName.FRUITING_TRIGGER);\n");
        sb.append("        }\n\n");

        sb.append("    }\n\n");
        return sb.toString();
    }

    /** Find a state that is NOT the fromState of this transition. */
    private String findWrongState(StateMachineDef sm, TransitionDef t) {
        for (String state : sm.states()) {
            if (!state.equals(t.fromState())) {
                return state;
            }
        }
        return sm.states().get(0); // fallback
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
