export enum ContaminationType {
  TRICHODERMA = 'TRICHODERMA',

  COBWEB = 'COBWEB',

  BLACK_MOLD = 'BLACK_MOLD',

  BACTERIAL_BLOTCH = 'BACTERIAL_BLOTCH',

  WET_BUBBLE = 'WET_BUBBLE',

  DRY_BUBBLE = 'DRY_BUBBLE',

  INSECT = 'INSECT',

  UNKNOWN = 'UNKNOWN',

  OTHER = 'OTHER',
}
