export enum ContaminationAction {
  ISOLATE = 'ISOLATE',

  REMOVE = 'REMOVE',

  SALT_TREATMENT = 'SALT_TREATMENT',

  PEROXIDE_TREATMENT = 'PEROXIDE_TREATMENT',

  INCREASED_VENTILATION = 'INCREASED_VENTILATION',

  DISCARD_BATCH = 'DISCARD_BATCH',

  MONITOR = 'MONITOR',
}
