export enum PhaseName {
  INOCULATION = 'INOCULATION',

  EARLY_COLONIZATION = 'EARLY_COLONIZATION',

  FULL_COLONIZATION = 'FULL_COLONIZATION',

  CONSOLIDATION = 'CONSOLIDATION',

  FRUITING_TRIGGER = 'FRUITING_TRIGGER',

  PRIMORDIA = 'PRIMORDIA',

  FRUITING_BODY_GROWTH = 'FRUITING_BODY_GROWTH',

  HARVEST = 'HARVEST',

  REHYDRATION_PAUSE = 'REHYDRATION_PAUSE',

  COMPLETED = 'COMPLETED',
}
