export enum RoomType {
  STERILE_ZONE = 'STERILE_ZONE',

  INCUBATION = 'INCUBATION',

  FRUITING_CHAMBER = 'FRUITING_CHAMBER',

  COLD_STORAGE = 'COLD_STORAGE',

  WORK_ZONE = 'WORK_ZONE',

  LABORATORY = 'LABORATORY',
}
