export enum StockMovementType {
  RECEIPT = 'RECEIPT',

  CONSUMPTION = 'CONSUMPTION',

  ADJUSTMENT_IN = 'ADJUSTMENT_IN',

  ADJUSTMENT_OUT = 'ADJUSTMENT_OUT',

  WASTE = 'WASTE',

  RETURN_TO_SUPPLIER = 'RETURN_TO_SUPPLIER',
}
