export enum SubstrateBase {
  WHEAT_STRAW = 'WHEAT_STRAW',

  BARLEY_STRAW = 'BARLEY_STRAW',

  BEECH_SAWDUST = 'BEECH_SAWDUST',

  OAK_SAWDUST = 'OAK_SAWDUST',

  CORN_COB = 'CORN_COB',

  SPENT_COFFEE_GROUNDS = 'SPENT_COFFEE_GROUNDS',

  BLENDED = 'BLENDED',
}
