package com.mcms.codegen.generator;

import com.mcms.codegen.model.StateMachineDef;
import com.mcms.codegen.model.TransitionDef;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.*;

/**
 * Tests for the StateMachineGenerator - validates JavaPoet code generation.
 */
@DisplayName("StateMachineGenerator")
class StateMachineGeneratorTest {

    @TempDir
    Path tempDir;

    private StateMachineDef createMinimalStateMachine() {
        return new StateMachineDef(
            "TestEntity",
            List.of("STATE_A", "STATE_B"),
            List.of(new TransitionDef(
                "STATE_A", "STATE_B", "moveToB",
                List.of(), Optional.of("isReady"), Optional.empty(),
                List.of("EntityMoved"), List.of("logTransition")
            )),
            List.of()
        );
    }

    private StateMachineDef createBatchLikeStateMachine() {
        return new StateMachineDef(
            "Batch",
            List.of("INOCULATION", "EARLY_COLONIZATION", "COMPLETED"),
            List.of(
                new TransitionDef(
                    "INOCULATION", "EARLY_COLONIZATION", "startColonization",
                    List.of(), Optional.of("substrateFullyInoculated"), Optional.empty(),
                    List.of("ColonizationStarted"), List.of("logPhaseStart", "updatePhaseExecution")
                ),
                new TransitionDef(
                    "EARLY_COLONIZATION", "COMPLETED", "endBatch",
                    List.of(), Optional.empty(), Optional.empty(),
                    List.of("BatchCompleted"), List.of("finalizeYieldCalculations")
                )
            ),
            List.of()
        );
    }

    @Test
    @DisplayName("should generate state machine class file")
    void shouldGenerateFile() throws IOException {
        StateMachineGenerator gen = new StateMachineGenerator(tempDir);
        gen.generate(createMinimalStateMachine());

        Path expectedFile = tempDir.resolve("com/mcms/statemachine/TestEntityStateMachine.java");
        assertThat(expectedFile).exists();
    }

    @Test
    @DisplayName("should include GENERATED header in output")
    void shouldIncludeGeneratedHeader() throws IOException {
        StateMachineGenerator gen = new StateMachineGenerator(tempDir);
        gen.generate(createMinimalStateMachine());

        Path file = tempDir.resolve("com/mcms/statemachine/TestEntityStateMachine.java");
        String content = Files.readString(file);
        assertThat(content).contains("GENERATED by MCMS Code Generator - DO NOT EDIT");
    }

    @Test
    @DisplayName("should generate transition method")
    void shouldGenerateTransitionMethod() throws IOException {
        StateMachineGenerator gen = new StateMachineGenerator(tempDir);
        gen.generate(createMinimalStateMachine());

        Path file = tempDir.resolve("com/mcms/statemachine/TestEntityStateMachine.java");
        String content = Files.readString(file);
        assertThat(content).contains("public void moveToB()");
    }

    @Test
    @DisplayName("should include assertState in transition methods")
    void shouldIncludeAssertState() throws IOException {
        StateMachineGenerator gen = new StateMachineGenerator(tempDir);
        gen.generate(createMinimalStateMachine());

        Path file = tempDir.resolve("com/mcms/statemachine/TestEntityStateMachine.java");
        String content = Files.readString(file);
        assertThat(content).contains("assertState(PhaseName.STATE_A)");
    }

    @Test
    @DisplayName("should generate guard stub method for simple guards")
    void shouldGenerateGuardStub() throws IOException {
        StateMachineGenerator gen = new StateMachineGenerator(tempDir);
        gen.generate(createMinimalStateMachine());

        Path file = tempDir.resolve("com/mcms/statemachine/TestEntityStateMachine.java");
        String content = Files.readString(file);
        assertThat(content).contains("protected boolean isReady()");
    }

    @Test
    @DisplayName("should generate action stub methods")
    void shouldGenerateActionStub() throws IOException {
        StateMachineGenerator gen = new StateMachineGenerator(tempDir);
        gen.generate(createMinimalStateMachine());

        Path file = tempDir.resolve("com/mcms/statemachine/TestEntityStateMachine.java");
        String content = Files.readString(file);
        assertThat(content).contains("protected void logTransition()");
    }

    @Test
    @DisplayName("should generate getCurrentState method")
    void shouldGenerateGetCurrentState() throws IOException {
        StateMachineGenerator gen = new StateMachineGenerator(tempDir);
        gen.generate(createMinimalStateMachine());

        Path file = tempDir.resolve("com/mcms/statemachine/TestEntityStateMachine.java");
        String content = Files.readString(file);
        assertThat(content).contains("public PhaseName getCurrentState()");
    }

    @Test
    @DisplayName("should generate Batch-like state machine with multiple transitions")
    void shouldGenerateBatchStateMachine() throws IOException {
        StateMachineGenerator gen = new StateMachineGenerator(tempDir);
        gen.generate(createBatchLikeStateMachine());

        Path file = tempDir.resolve("com/mcms/statemachine/BatchStateMachine.java");
        String content = Files.readString(file);
        assertThat(content).contains("public void startColonization()");
        assertThat(content).contains("public void endBatch()");
        assertThat(content).contains("protected boolean substrateFullyInoculated()");
        assertThat(content).contains("protected void logPhaseStart()");
        assertThat(content).contains("protected void updatePhaseExecution()");
        assertThat(content).contains("protected void finalizeYieldCalculations()");
    }
}
