package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BatchMaterialUsageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchMaterialUsageAllPropertiesEquals(BatchMaterialUsage expected, BatchMaterialUsage actual) {
        assertBatchMaterialUsageAutoGeneratedPropertiesEquals(expected, actual);
        assertBatchMaterialUsageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchMaterialUsageAllUpdatablePropertiesEquals(BatchMaterialUsage expected, BatchMaterialUsage actual) {
        assertBatchMaterialUsageUpdatableFieldsEquals(expected, actual);
        assertBatchMaterialUsageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchMaterialUsageAutoGeneratedPropertiesEquals(BatchMaterialUsage expected, BatchMaterialUsage actual) {
        assertThat(actual)
            .as("Verify BatchMaterialUsage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchMaterialUsageUpdatableFieldsEquals(BatchMaterialUsage expected, BatchMaterialUsage actual) {
        assertThat(actual)
            .as("Verify BatchMaterialUsage relevant properties")
            .satisfies(a -> assertThat(a.getUsageDate()).as("check usageDate").isEqualTo(expected.getUsageDate()))
            .satisfies(a ->
                assertThat(a.getQuantityUsed())
                    .as("check quantityUsed")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantityUsed())
            )
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a -> assertThat(a.getPurpose()).as("check purpose").isEqualTo(expected.getPurpose()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchMaterialUsageUpdatableRelationshipsEquals(BatchMaterialUsage expected, BatchMaterialUsage actual) {
        assertThat(actual)
            .as("Verify BatchMaterialUsage relationships")
            .satisfies(a -> assertThat(a.getBatch()).as("check batch").isEqualTo(expected.getBatch()))
            .satisfies(a -> assertThat(a.getInventoryLot()).as("check inventoryLot").isEqualTo(expected.getInventoryLot()))
            .satisfies(a -> assertThat(a.getMaterial()).as("check material").isEqualTo(expected.getMaterial()));
    }
}
