package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BatchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchAllPropertiesEquals(Batch expected, Batch actual) {
        assertBatchAutoGeneratedPropertiesEquals(expected, actual);
        assertBatchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchAllUpdatablePropertiesEquals(Batch expected, Batch actual) {
        assertBatchUpdatableFieldsEquals(expected, actual);
        assertBatchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchAutoGeneratedPropertiesEquals(Batch expected, Batch actual) {
        assertThat(actual)
            .as("Verify Batch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchUpdatableFieldsEquals(Batch expected, Batch actual) {
        assertThat(actual)
            .as("Verify Batch relevant properties")
            .satisfies(a -> assertThat(a.getBatchCode()).as("check batchCode").isEqualTo(expected.getBatchCode()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getCurrentPhase()).as("check currentPhase").isEqualTo(expected.getCurrentPhase()))
            .satisfies(a -> assertThat(a.getNumberOfBags()).as("check numberOfBags").isEqualTo(expected.getNumberOfBags()))
            .satisfies(a ->
                assertThat(a.getSubstrateWeightKg())
                    .as("check substrateWeightKg")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSubstrateWeightKg())
            )
            .satisfies(a ->
                assertThat(a.getSpawnWeightKg())
                    .as("check spawnWeightKg")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSpawnWeightKg())
            )
            .satisfies(a ->
                assertThat(a.getTargetYieldKg())
                    .as("check targetYieldKg")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTargetYieldKg())
            )
            .satisfies(a ->
                assertThat(a.getActualTotalYieldKg())
                    .as("check actualTotalYieldKg")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getActualTotalYieldKg())
            )
            .satisfies(a ->
                assertThat(a.getBiologicalEfficiencyPercent())
                    .as("check biologicalEfficiencyPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBiologicalEfficiencyPercent())
            )
            .satisfies(a -> assertThat(a.getIsContaminated()).as("check isContaminated").isEqualTo(expected.getIsContaminated()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCompletionNote()).as("check completionNote").isEqualTo(expected.getCompletionNote()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBatchUpdatableRelationshipsEquals(Batch expected, Batch actual) {
        assertThat(actual)
            .as("Verify Batch relationships")
            .satisfies(a -> assertThat(a.getStrain()).as("check strain").isEqualTo(expected.getStrain()))
            .satisfies(a -> assertThat(a.getRecipe()).as("check recipe").isEqualTo(expected.getRecipe()));
    }
}
