package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ContaminationEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaminationEventAllPropertiesEquals(ContaminationEvent expected, ContaminationEvent actual) {
        assertContaminationEventAutoGeneratedPropertiesEquals(expected, actual);
        assertContaminationEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaminationEventAllUpdatablePropertiesEquals(ContaminationEvent expected, ContaminationEvent actual) {
        assertContaminationEventUpdatableFieldsEquals(expected, actual);
        assertContaminationEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaminationEventAutoGeneratedPropertiesEquals(ContaminationEvent expected, ContaminationEvent actual) {
        assertThat(actual)
            .as("Verify ContaminationEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaminationEventUpdatableFieldsEquals(ContaminationEvent expected, ContaminationEvent actual) {
        assertThat(actual)
            .as("Verify ContaminationEvent relevant properties")
            .satisfies(a -> assertThat(a.getDetectedDate()).as("check detectedDate").isEqualTo(expected.getDetectedDate()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getSeverity()).as("check severity").isEqualTo(expected.getSeverity()))
            .satisfies(a -> assertThat(a.getAffectedBags()).as("check affectedBags").isEqualTo(expected.getAffectedBags()))
            .satisfies(a ->
                assertThat(a.getAffectedPercentage())
                    .as("check affectedPercentage")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAffectedPercentage())
            )
            .satisfies(a -> assertThat(a.getActionTaken()).as("check actionTaken").isEqualTo(expected.getActionTaken()))
            .satisfies(a -> assertThat(a.getResolvedDate()).as("check resolvedDate").isEqualTo(expected.getResolvedDate()))
            .satisfies(a ->
                assertThat(a.getLossKg()).as("check lossKg").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLossKg())
            )
            .satisfies(a -> assertThat(a.getRootCauseAnalysis()).as("check rootCauseAnalysis").isEqualTo(expected.getRootCauseAnalysis()))
            .satisfies(a -> assertThat(a.getPreventiveMeasures()).as("check preventiveMeasures").isEqualTo(expected.getPreventiveMeasures())
            )
            .satisfies(a -> assertThat(a.getDetectedBy()).as("check detectedBy").isEqualTo(expected.getDetectedBy()))
            .satisfies(a -> assertThat(a.getPhotosReference()).as("check photosReference").isEqualTo(expected.getPhotosReference()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaminationEventUpdatableRelationshipsEquals(ContaminationEvent expected, ContaminationEvent actual) {
        assertThat(actual)
            .as("Verify ContaminationEvent relationships")
            .satisfies(a -> assertThat(a.getBatch()).as("check batch").isEqualTo(expected.getBatch()))
            .satisfies(a -> assertThat(a.getPhaseExecution()).as("check phaseExecution").isEqualTo(expected.getPhaseExecution()))
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()));
    }
}
