package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CostRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCostRecordAllPropertiesEquals(CostRecord expected, CostRecord actual) {
        assertCostRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertCostRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCostRecordAllUpdatablePropertiesEquals(CostRecord expected, CostRecord actual) {
        assertCostRecordUpdatableFieldsEquals(expected, actual);
        assertCostRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCostRecordAutoGeneratedPropertiesEquals(CostRecord expected, CostRecord actual) {
        assertThat(actual)
            .as("Verify CostRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCostRecordUpdatableFieldsEquals(CostRecord expected, CostRecord actual) {
        assertThat(actual)
            .as("Verify CostRecord relevant properties")
            .satisfies(a -> assertThat(a.getRecordDate()).as("check recordDate").isEqualTo(expected.getRecordDate()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCostRecordUpdatableRelationshipsEquals(CostRecord expected, CostRecord actual) {
        assertThat(actual)
            .as("Verify CostRecord relationships")
            .satisfies(a -> assertThat(a.getBatch()).as("check batch").isEqualTo(expected.getBatch()));
    }
}
