package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class EnvironmentalAlertAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvironmentalAlertAllPropertiesEquals(EnvironmentalAlert expected, EnvironmentalAlert actual) {
        assertEnvironmentalAlertAutoGeneratedPropertiesEquals(expected, actual);
        assertEnvironmentalAlertAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvironmentalAlertAllUpdatablePropertiesEquals(EnvironmentalAlert expected, EnvironmentalAlert actual) {
        assertEnvironmentalAlertUpdatableFieldsEquals(expected, actual);
        assertEnvironmentalAlertUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvironmentalAlertAutoGeneratedPropertiesEquals(EnvironmentalAlert expected, EnvironmentalAlert actual) {
        assertThat(actual)
            .as("Verify EnvironmentalAlert auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvironmentalAlertUpdatableFieldsEquals(EnvironmentalAlert expected, EnvironmentalAlert actual) {
        assertThat(actual)
            .as("Verify EnvironmentalAlert relevant properties")
            .satisfies(a -> assertThat(a.getAlertTime()).as("check alertTime").isEqualTo(expected.getAlertTime()))
            .satisfies(a -> assertThat(a.getSeverity()).as("check severity").isEqualTo(expected.getSeverity()))
            .satisfies(a -> assertThat(a.getParameter()).as("check parameter").isEqualTo(expected.getParameter()))
            .satisfies(a ->
                assertThat(a.getActualValue())
                    .as("check actualValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getActualValue())
            )
            .satisfies(a ->
                assertThat(a.getThresholdValue())
                    .as("check thresholdValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getThresholdValue())
            )
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getAcknowledged()).as("check acknowledged").isEqualTo(expected.getAcknowledged()))
            .satisfies(a -> assertThat(a.getAcknowledgedBy()).as("check acknowledgedBy").isEqualTo(expected.getAcknowledgedBy()))
            .satisfies(a -> assertThat(a.getAcknowledgedAt()).as("check acknowledgedAt").isEqualTo(expected.getAcknowledgedAt()))
            .satisfies(a -> assertThat(a.getResolutionNote()).as("check resolutionNote").isEqualTo(expected.getResolutionNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvironmentalAlertUpdatableRelationshipsEquals(EnvironmentalAlert expected, EnvironmentalAlert actual) {
        assertThat(actual)
            .as("Verify EnvironmentalAlert relationships")
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()))
            .satisfies(a -> assertThat(a.getSensor()).as("check sensor").isEqualTo(expected.getSensor()))
            .satisfies(a -> assertThat(a.getBatch()).as("check batch").isEqualTo(expected.getBatch()));
    }
}
