package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class EnvironmentalTargetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvironmentalTargetAllPropertiesEquals(EnvironmentalTarget expected, EnvironmentalTarget actual) {
        assertEnvironmentalTargetAutoGeneratedPropertiesEquals(expected, actual);
        assertEnvironmentalTargetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvironmentalTargetAllUpdatablePropertiesEquals(EnvironmentalTarget expected, EnvironmentalTarget actual) {
        assertEnvironmentalTargetUpdatableFieldsEquals(expected, actual);
        assertEnvironmentalTargetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvironmentalTargetAutoGeneratedPropertiesEquals(EnvironmentalTarget expected, EnvironmentalTarget actual) {
        assertThat(actual)
            .as("Verify EnvironmentalTarget auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvironmentalTargetUpdatableFieldsEquals(EnvironmentalTarget expected, EnvironmentalTarget actual) {
        assertThat(actual)
            .as("Verify EnvironmentalTarget relevant properties")
            .satisfies(a -> assertThat(a.getPhase()).as("check phase").isEqualTo(expected.getPhase()))
            .satisfies(a ->
                assertThat(a.getTempMinC()).as("check tempMinC").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTempMinC())
            )
            .satisfies(a ->
                assertThat(a.getTempMaxC()).as("check tempMaxC").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTempMaxC())
            )
            .satisfies(a ->
                assertThat(a.getHumidityMinPercent())
                    .as("check humidityMinPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getHumidityMinPercent())
            )
            .satisfies(a ->
                assertThat(a.getHumidityMaxPercent())
                    .as("check humidityMaxPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getHumidityMaxPercent())
            )
            .satisfies(a -> assertThat(a.getCo2MaxPpm()).as("check co2MaxPpm").isEqualTo(expected.getCo2MaxPpm()))
            .satisfies(a -> assertThat(a.getLightLux()).as("check lightLux").isEqualTo(expected.getLightLux()))
            .satisfies(a ->
                assertThat(a.getFreshAirExchangesPerHour())
                    .as("check freshAirExchangesPerHour")
                    .isEqualTo(expected.getFreshAirExchangesPerHour())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvironmentalTargetUpdatableRelationshipsEquals(EnvironmentalTarget expected, EnvironmentalTarget actual) {
        assertThat(actual)
            .as("Verify EnvironmentalTarget relationships")
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()));
    }
}
