package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FlushCycleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlushCycleAllPropertiesEquals(FlushCycle expected, FlushCycle actual) {
        assertFlushCycleAutoGeneratedPropertiesEquals(expected, actual);
        assertFlushCycleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlushCycleAllUpdatablePropertiesEquals(FlushCycle expected, FlushCycle actual) {
        assertFlushCycleUpdatableFieldsEquals(expected, actual);
        assertFlushCycleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlushCycleAutoGeneratedPropertiesEquals(FlushCycle expected, FlushCycle actual) {
        assertThat(actual)
            .as("Verify FlushCycle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlushCycleUpdatableFieldsEquals(FlushCycle expected, FlushCycle actual) {
        assertThat(actual)
            .as("Verify FlushCycle relevant properties")
            .satisfies(a -> assertThat(a.getFlushNumber()).as("check flushNumber").isEqualTo(expected.getFlushNumber()))
            .satisfies(a -> assertThat(a.getHarvestStartDate()).as("check harvestStartDate").isEqualTo(expected.getHarvestStartDate()))
            .satisfies(a -> assertThat(a.getHarvestEndDate()).as("check harvestEndDate").isEqualTo(expected.getHarvestEndDate()))
            .satisfies(a ->
                assertThat(a.getYieldKg()).as("check yieldKg").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getYieldKg())
            )
            .satisfies(a -> assertThat(a.getYieldBagsHarvested()).as("check yieldBagsHarvested").isEqualTo(expected.getYieldBagsHarvested())
            )
            .satisfies(a ->
                assertThat(a.getAvgFruitBodyWeightG())
                    .as("check avgFruitBodyWeightG")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAvgFruitBodyWeightG())
            )
            .satisfies(a -> assertThat(a.getRehydrationDone()).as("check rehydrationDone").isEqualTo(expected.getRehydrationDone()))
            .satisfies(a ->
                assertThat(a.getRehydrationDurationHours())
                    .as("check rehydrationDurationHours")
                    .isEqualTo(expected.getRehydrationDurationHours())
            )
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlushCycleUpdatableRelationshipsEquals(FlushCycle expected, FlushCycle actual) {
        assertThat(actual)
            .as("Verify FlushCycle relationships")
            .satisfies(a -> assertThat(a.getBatch()).as("check batch").isEqualTo(expected.getBatch()));
    }
}
