package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class HarvestRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestRecordAllPropertiesEquals(HarvestRecord expected, HarvestRecord actual) {
        assertHarvestRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertHarvestRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestRecordAllUpdatablePropertiesEquals(HarvestRecord expected, HarvestRecord actual) {
        assertHarvestRecordUpdatableFieldsEquals(expected, actual);
        assertHarvestRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestRecordAutoGeneratedPropertiesEquals(HarvestRecord expected, HarvestRecord actual) {
        assertThat(actual)
            .as("Verify HarvestRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestRecordUpdatableFieldsEquals(HarvestRecord expected, HarvestRecord actual) {
        assertThat(actual)
            .as("Verify HarvestRecord relevant properties")
            .satisfies(a -> assertThat(a.getHarvestDate()).as("check harvestDate").isEqualTo(expected.getHarvestDate()))
            .satisfies(a ->
                assertThat(a.getWeightKg()).as("check weightKg").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getWeightKg())
            )
            .satisfies(a -> assertThat(a.getGrade()).as("check grade").isEqualTo(expected.getGrade()))
            .satisfies(a -> assertThat(a.getPickerName()).as("check pickerName").isEqualTo(expected.getPickerName()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHarvestRecordUpdatableRelationshipsEquals(HarvestRecord expected, HarvestRecord actual) {
        assertThat(actual)
            .as("Verify HarvestRecord relationships")
            .satisfies(a -> assertThat(a.getFlushCycle()).as("check flushCycle").isEqualTo(expected.getFlushCycle()));
    }
}
