package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InventoryLotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryLotAllPropertiesEquals(InventoryLot expected, InventoryLot actual) {
        assertInventoryLotAutoGeneratedPropertiesEquals(expected, actual);
        assertInventoryLotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryLotAllUpdatablePropertiesEquals(InventoryLot expected, InventoryLot actual) {
        assertInventoryLotUpdatableFieldsEquals(expected, actual);
        assertInventoryLotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryLotAutoGeneratedPropertiesEquals(InventoryLot expected, InventoryLot actual) {
        assertThat(actual)
            .as("Verify InventoryLot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryLotUpdatableFieldsEquals(InventoryLot expected, InventoryLot actual) {
        assertThat(actual)
            .as("Verify InventoryLot relevant properties")
            .satisfies(a -> assertThat(a.getLotCode()).as("check lotCode").isEqualTo(expected.getLotCode()))
            .satisfies(a -> assertThat(a.getReceivedDate()).as("check receivedDate").isEqualTo(expected.getReceivedDate()))
            .satisfies(a ->
                assertThat(a.getQuantityReceived())
                    .as("check quantityReceived")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantityReceived())
            )
            .satisfies(a ->
                assertThat(a.getQuantityOnHand())
                    .as("check quantityOnHand")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantityOnHand())
            )
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a -> assertThat(a.getExpiryDate()).as("check expiryDate").isEqualTo(expected.getExpiryDate()))
            .satisfies(a -> assertThat(a.getStorageLocation()).as("check storageLocation").isEqualTo(expected.getStorageLocation()))
            .satisfies(a -> assertThat(a.getSupplierLotNumber()).as("check supplierLotNumber").isEqualTo(expected.getSupplierLotNumber()))
            .satisfies(a -> assertThat(a.getIsExhausted()).as("check isExhausted").isEqualTo(expected.getIsExhausted()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryLotUpdatableRelationshipsEquals(InventoryLot expected, InventoryLot actual) {
        assertThat(actual)
            .as("Verify InventoryLot relationships")
            .satisfies(a -> assertThat(a.getMaterial()).as("check material").isEqualTo(expected.getMaterial()))
            .satisfies(a -> assertThat(a.getSupplyOrderLine()).as("check supplyOrderLine").isEqualTo(expected.getSupplyOrderLine()));
    }
}
