package com.mcms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MandatoryFieldCheckAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMandatoryFieldCheckAllPropertiesEquals(MandatoryFieldCheck expected, MandatoryFieldCheck actual) {
        assertMandatoryFieldCheckAutoGeneratedPropertiesEquals(expected, actual);
        assertMandatoryFieldCheckAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMandatoryFieldCheckAllUpdatablePropertiesEquals(MandatoryFieldCheck expected, MandatoryFieldCheck actual) {
        assertMandatoryFieldCheckUpdatableFieldsEquals(expected, actual);
        assertMandatoryFieldCheckUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMandatoryFieldCheckAutoGeneratedPropertiesEquals(MandatoryFieldCheck expected, MandatoryFieldCheck actual) {
        assertThat(actual)
            .as("Verify MandatoryFieldCheck auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMandatoryFieldCheckUpdatableFieldsEquals(MandatoryFieldCheck expected, MandatoryFieldCheck actual) {
        assertThat(actual)
            .as("Verify MandatoryFieldCheck relevant properties")
            .satisfies(a -> assertThat(a.getFieldName()).as("check fieldName").isEqualTo(expected.getFieldName()))
            .satisfies(a -> assertThat(a.getIsFilled()).as("check isFilled").isEqualTo(expected.getIsFilled()))
            .satisfies(a -> assertThat(a.getCheckDate()).as("check checkDate").isEqualTo(expected.getCheckDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMandatoryFieldCheckUpdatableRelationshipsEquals(MandatoryFieldCheck expected, MandatoryFieldCheck actual) {
        assertThat(actual)
            .as("Verify MandatoryFieldCheck relationships")
            .satisfies(a -> assertThat(a.getPhaseExecution()).as("check phaseExecution").isEqualTo(expected.getPhaseExecution()));
    }
}
