package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MonthlyReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonthlyReportAllPropertiesEquals(MonthlyReport expected, MonthlyReport actual) {
        assertMonthlyReportAutoGeneratedPropertiesEquals(expected, actual);
        assertMonthlyReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonthlyReportAllUpdatablePropertiesEquals(MonthlyReport expected, MonthlyReport actual) {
        assertMonthlyReportUpdatableFieldsEquals(expected, actual);
        assertMonthlyReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonthlyReportAutoGeneratedPropertiesEquals(MonthlyReport expected, MonthlyReport actual) {
        assertThat(actual)
            .as("Verify MonthlyReport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonthlyReportUpdatableFieldsEquals(MonthlyReport expected, MonthlyReport actual) {
        assertThat(actual)
            .as("Verify MonthlyReport relevant properties")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getMonth()).as("check month").isEqualTo(expected.getMonth()))
            .satisfies(a -> assertThat(a.getGeneratedAt()).as("check generatedAt").isEqualTo(expected.getGeneratedAt()))
            .satisfies(a ->
                assertThat(a.getTotalYieldKg())
                    .as("check totalYieldKg")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalYieldKg())
            )
            .satisfies(a ->
                assertThat(a.getTotalCost()).as("check totalCost").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotalCost())
            )
            .satisfies(a ->
                assertThat(a.getTotalRevenue())
                    .as("check totalRevenue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalRevenue())
            )
            .satisfies(a ->
                assertThat(a.getProfitMarginPercent())
                    .as("check profitMarginPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getProfitMarginPercent())
            )
            .satisfies(a ->
                assertThat(a.getTotalContaminationEvents())
                    .as("check totalContaminationEvents")
                    .isEqualTo(expected.getTotalContaminationEvents())
            )
            .satisfies(a -> assertThat(a.getTotalMissingFields()).as("check totalMissingFields").isEqualTo(expected.getTotalMissingFields())
            )
            .satisfies(a -> assertThat(a.getSummary()).as("check summary").isEqualTo(expected.getSummary()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonthlyReportUpdatableRelationshipsEquals(MonthlyReport expected, MonthlyReport actual) {
        assertThat(actual)
            .as("Verify MonthlyReport relationships")
            .satisfies(a -> assertThat(a.getBatch()).as("check batch").isEqualTo(expected.getBatch()));
    }
}
