package com.mcms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PhaseExecutionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhaseExecutionAllPropertiesEquals(PhaseExecution expected, PhaseExecution actual) {
        assertPhaseExecutionAutoGeneratedPropertiesEquals(expected, actual);
        assertPhaseExecutionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhaseExecutionAllUpdatablePropertiesEquals(PhaseExecution expected, PhaseExecution actual) {
        assertPhaseExecutionUpdatableFieldsEquals(expected, actual);
        assertPhaseExecutionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhaseExecutionAutoGeneratedPropertiesEquals(PhaseExecution expected, PhaseExecution actual) {
        assertThat(actual)
            .as("Verify PhaseExecution auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhaseExecutionUpdatableFieldsEquals(PhaseExecution expected, PhaseExecution actual) {
        assertThat(actual)
            .as("Verify PhaseExecution relevant properties")
            .satisfies(a -> assertThat(a.getPhase()).as("check phase").isEqualTo(expected.getPhase()))
            .satisfies(a -> assertThat(a.getSequenceOrder()).as("check sequenceOrder").isEqualTo(expected.getSequenceOrder()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a ->
                assertThat(a.getPlannedDurationDays()).as("check plannedDurationDays").isEqualTo(expected.getPlannedDurationDays())
            )
            .satisfies(a -> assertThat(a.getActualDurationDays()).as("check actualDurationDays").isEqualTo(expected.getActualDurationDays())
            )
            .satisfies(a -> assertThat(a.getResponsiblePerson()).as("check responsiblePerson").isEqualTo(expected.getResponsiblePerson()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhaseExecutionUpdatableRelationshipsEquals(PhaseExecution expected, PhaseExecution actual) {
        assertThat(actual)
            .as("Verify PhaseExecution relationships")
            .satisfies(a -> assertThat(a.getBatch()).as("check batch").isEqualTo(expected.getBatch()))
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()));
    }
}
