package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SalesOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesOrderAllPropertiesEquals(SalesOrder expected, SalesOrder actual) {
        assertSalesOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertSalesOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesOrderAllUpdatablePropertiesEquals(SalesOrder expected, SalesOrder actual) {
        assertSalesOrderUpdatableFieldsEquals(expected, actual);
        assertSalesOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesOrderAutoGeneratedPropertiesEquals(SalesOrder expected, SalesOrder actual) {
        assertThat(actual)
            .as("Verify SalesOrder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesOrderUpdatableFieldsEquals(SalesOrder expected, SalesOrder actual) {
        assertThat(actual)
            .as("Verify SalesOrder relevant properties")
            .satisfies(a -> assertThat(a.getOrderCode()).as("check orderCode").isEqualTo(expected.getOrderCode()))
            .satisfies(a -> assertThat(a.getOrderDate()).as("check orderDate").isEqualTo(expected.getOrderDate()))
            .satisfies(a ->
                assertThat(a.getRequestedDeliveryDate()).as("check requestedDeliveryDate").isEqualTo(expected.getRequestedDeliveryDate())
            )
            .satisfies(a -> assertThat(a.getActualDeliveryDate()).as("check actualDeliveryDate").isEqualTo(expected.getActualDeliveryDate())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getTotalWeight())
                    .as("check totalWeight")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalWeight())
            )
            .satisfies(a ->
                assertThat(a.getTotalRevenue())
                    .as("check totalRevenue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalRevenue())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getInvoiceNumber()).as("check invoiceNumber").isEqualTo(expected.getInvoiceNumber()))
            .satisfies(a -> assertThat(a.getPaymentStatus()).as("check paymentStatus").isEqualTo(expected.getPaymentStatus()))
            .satisfies(a -> assertThat(a.getPaymentDueDate()).as("check paymentDueDate").isEqualTo(expected.getPaymentDueDate()))
            .satisfies(a ->
                assertThat(a.getPaymentReceivedDate()).as("check paymentReceivedDate").isEqualTo(expected.getPaymentReceivedDate())
            )
            .satisfies(a -> assertThat(a.getShippingAddress()).as("check shippingAddress").isEqualTo(expected.getShippingAddress()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesOrderUpdatableRelationshipsEquals(SalesOrder expected, SalesOrder actual) {
        assertThat(actual)
            .as("Verify SalesOrder relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
