package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SalesOrderLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesOrderLineAllPropertiesEquals(SalesOrderLine expected, SalesOrderLine actual) {
        assertSalesOrderLineAutoGeneratedPropertiesEquals(expected, actual);
        assertSalesOrderLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesOrderLineAllUpdatablePropertiesEquals(SalesOrderLine expected, SalesOrderLine actual) {
        assertSalesOrderLineUpdatableFieldsEquals(expected, actual);
        assertSalesOrderLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesOrderLineAutoGeneratedPropertiesEquals(SalesOrderLine expected, SalesOrderLine actual) {
        assertThat(actual)
            .as("Verify SalesOrderLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesOrderLineUpdatableFieldsEquals(SalesOrderLine expected, SalesOrderLine actual) {
        assertThat(actual)
            .as("Verify SalesOrderLine relevant properties")
            .satisfies(a -> assertThat(a.getLineNumber()).as("check lineNumber").isEqualTo(expected.getLineNumber()))
            .satisfies(a ->
                assertThat(a.getWeightKg()).as("check weightKg").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getWeightKg())
            )
            .satisfies(a -> assertThat(a.getGrade()).as("check grade").isEqualTo(expected.getGrade()))
            .satisfies(a -> assertThat(a.getQuantityUnits()).as("check quantityUnits").isEqualTo(expected.getQuantityUnits()))
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a ->
                assertThat(a.getPricePerKg())
                    .as("check pricePerKg")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPricePerKg())
            )
            .satisfies(a ->
                assertThat(a.getLineTotal()).as("check lineTotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLineTotal())
            )
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesOrderLineUpdatableRelationshipsEquals(SalesOrderLine expected, SalesOrderLine actual) {
        assertThat(actual)
            .as("Verify SalesOrderLine relationships")
            .satisfies(a -> assertThat(a.getSalesOrder()).as("check salesOrder").isEqualTo(expected.getSalesOrder()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()))
            .satisfies(a -> assertThat(a.getBatch()).as("check batch").isEqualTo(expected.getBatch()));
    }
}
