package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SensorReadingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensorReadingAllPropertiesEquals(SensorReading expected, SensorReading actual) {
        assertSensorReadingAutoGeneratedPropertiesEquals(expected, actual);
        assertSensorReadingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensorReadingAllUpdatablePropertiesEquals(SensorReading expected, SensorReading actual) {
        assertSensorReadingUpdatableFieldsEquals(expected, actual);
        assertSensorReadingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensorReadingAutoGeneratedPropertiesEquals(SensorReading expected, SensorReading actual) {
        assertThat(actual)
            .as("Verify SensorReading auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensorReadingUpdatableFieldsEquals(SensorReading expected, SensorReading actual) {
        assertThat(actual)
            .as("Verify SensorReading relevant properties")
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSensorReadingUpdatableRelationshipsEquals(SensorReading expected, SensorReading actual) {
        assertThat(actual)
            .as("Verify SensorReading relationships")
            .satisfies(a -> assertThat(a.getSensor()).as("check sensor").isEqualTo(expected.getSensor()));
    }
}
