package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class StrainAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrainAllPropertiesEquals(Strain expected, Strain actual) {
        assertStrainAutoGeneratedPropertiesEquals(expected, actual);
        assertStrainAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrainAllUpdatablePropertiesEquals(Strain expected, Strain actual) {
        assertStrainUpdatableFieldsEquals(expected, actual);
        assertStrainUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrainAutoGeneratedPropertiesEquals(Strain expected, Strain actual) {
        assertThat(actual)
            .as("Verify Strain auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrainUpdatableFieldsEquals(Strain expected, Strain actual) {
        assertThat(actual)
            .as("Verify Strain relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSpecies()).as("check species").isEqualTo(expected.getSpecies()))
            .satisfies(a -> assertThat(a.getVariety()).as("check variety").isEqualTo(expected.getVariety()))
            .satisfies(a ->
                assertThat(a.getOptimalTempMinC())
                    .as("check optimalTempMinC")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOptimalTempMinC())
            )
            .satisfies(a ->
                assertThat(a.getOptimalTempMaxC())
                    .as("check optimalTempMaxC")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOptimalTempMaxC())
            )
            .satisfies(a ->
                assertThat(a.getOptimalHumidityMin())
                    .as("check optimalHumidityMin")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOptimalHumidityMin())
            )
            .satisfies(a ->
                assertThat(a.getOptimalHumidityMax())
                    .as("check optimalHumidityMax")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOptimalHumidityMax())
            )
            .satisfies(a -> assertThat(a.getOptimalCO2MaxPpm()).as("check optimalCO2MaxPpm").isEqualTo(expected.getOptimalCO2MaxPpm()))
            .satisfies(a ->
                assertThat(a.getColonizationDaysMin()).as("check colonizationDaysMin").isEqualTo(expected.getColonizationDaysMin())
            )
            .satisfies(a ->
                assertThat(a.getColonizationDaysMax()).as("check colonizationDaysMax").isEqualTo(expected.getColonizationDaysMax())
            )
            .satisfies(a ->
                assertThat(a.getExpectedYieldPercent())
                    .as("check expectedYieldPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getExpectedYieldPercent())
            )
            .satisfies(a -> assertThat(a.getShelfLifeDays()).as("check shelfLifeDays").isEqualTo(expected.getShelfLifeDays()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrainUpdatableRelationshipsEquals(Strain expected, Strain actual) {
        // empty method
    }
}
