package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SubstrateRecipeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubstrateRecipeAllPropertiesEquals(SubstrateRecipe expected, SubstrateRecipe actual) {
        assertSubstrateRecipeAutoGeneratedPropertiesEquals(expected, actual);
        assertSubstrateRecipeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubstrateRecipeAllUpdatablePropertiesEquals(SubstrateRecipe expected, SubstrateRecipe actual) {
        assertSubstrateRecipeUpdatableFieldsEquals(expected, actual);
        assertSubstrateRecipeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubstrateRecipeAutoGeneratedPropertiesEquals(SubstrateRecipe expected, SubstrateRecipe actual) {
        assertThat(actual)
            .as("Verify SubstrateRecipe auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubstrateRecipeUpdatableFieldsEquals(SubstrateRecipe expected, SubstrateRecipe actual) {
        assertThat(actual)
            .as("Verify SubstrateRecipe relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getBaseType()).as("check baseType").isEqualTo(expected.getBaseType()))
            .satisfies(a -> assertThat(a.getCompositionDetail()).as("check compositionDetail").isEqualTo(expected.getCompositionDetail()))
            .satisfies(a ->
                assertThat(a.getSterilizationMethod()).as("check sterilizationMethod").isEqualTo(expected.getSterilizationMethod())
            )
            .satisfies(a ->
                assertThat(a.getMoistureTargetPercent())
                    .as("check moistureTargetPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMoistureTargetPercent())
            )
            .satisfies(a ->
                assertThat(a.getPhTarget()).as("check phTarget").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPhTarget())
            )
            .satisfies(a -> assertThat(a.getSupplementNotes()).as("check supplementNotes").isEqualTo(expected.getSupplementNotes()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubstrateRecipeUpdatableRelationshipsEquals(SubstrateRecipe expected, SubstrateRecipe actual) {
        // empty method
    }
}
