package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SupplyOrderLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplyOrderLineAllPropertiesEquals(SupplyOrderLine expected, SupplyOrderLine actual) {
        assertSupplyOrderLineAutoGeneratedPropertiesEquals(expected, actual);
        assertSupplyOrderLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplyOrderLineAllUpdatablePropertiesEquals(SupplyOrderLine expected, SupplyOrderLine actual) {
        assertSupplyOrderLineUpdatableFieldsEquals(expected, actual);
        assertSupplyOrderLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplyOrderLineAutoGeneratedPropertiesEquals(SupplyOrderLine expected, SupplyOrderLine actual) {
        assertThat(actual)
            .as("Verify SupplyOrderLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplyOrderLineUpdatableFieldsEquals(SupplyOrderLine expected, SupplyOrderLine actual) {
        assertThat(actual)
            .as("Verify SupplyOrderLine relevant properties")
            .satisfies(a -> assertThat(a.getLineNumber()).as("check lineNumber").isEqualTo(expected.getLineNumber()))
            .satisfies(a -> assertThat(a.getItemDescription()).as("check itemDescription").isEqualTo(expected.getItemDescription()))
            .satisfies(a ->
                assertThat(a.getQuantityOrdered())
                    .as("check quantityOrdered")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantityOrdered())
            )
            .satisfies(a ->
                assertThat(a.getQuantityReceived())
                    .as("check quantityReceived")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantityReceived())
            )
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a ->
                assertThat(a.getLineTotal()).as("check lineTotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLineTotal())
            )
            .satisfies(a -> assertThat(a.getLotNumber()).as("check lotNumber").isEqualTo(expected.getLotNumber()))
            .satisfies(a -> assertThat(a.getExpiryDate()).as("check expiryDate").isEqualTo(expected.getExpiryDate()))
            .satisfies(a -> assertThat(a.getQualityOnReceipt()).as("check qualityOnReceipt").isEqualTo(expected.getQualityOnReceipt()))
            .satisfies(a -> assertThat(a.getIsReceived()).as("check isReceived").isEqualTo(expected.getIsReceived()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplyOrderLineUpdatableRelationshipsEquals(SupplyOrderLine expected, SupplyOrderLine actual) {
        assertThat(actual)
            .as("Verify SupplyOrderLine relationships")
            .satisfies(a -> assertThat(a.getSupplyOrder()).as("check supplyOrder").isEqualTo(expected.getSupplyOrder()))
            .satisfies(a -> assertThat(a.getMaterial()).as("check material").isEqualTo(expected.getMaterial()))
            .satisfies(a -> assertThat(a.getBatch()).as("check batch").isEqualTo(expected.getBatch()));
    }
}
