package com.mcms.domain;

import static com.mcms.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SupplyOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplyOrderAllPropertiesEquals(SupplyOrder expected, SupplyOrder actual) {
        assertSupplyOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertSupplyOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplyOrderAllUpdatablePropertiesEquals(SupplyOrder expected, SupplyOrder actual) {
        assertSupplyOrderUpdatableFieldsEquals(expected, actual);
        assertSupplyOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplyOrderAutoGeneratedPropertiesEquals(SupplyOrder expected, SupplyOrder actual) {
        assertThat(actual)
            .as("Verify SupplyOrder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplyOrderUpdatableFieldsEquals(SupplyOrder expected, SupplyOrder actual) {
        assertThat(actual)
            .as("Verify SupplyOrder relevant properties")
            .satisfies(a -> assertThat(a.getOrderCode()).as("check orderCode").isEqualTo(expected.getOrderCode()))
            .satisfies(a -> assertThat(a.getOrderDate()).as("check orderDate").isEqualTo(expected.getOrderDate()))
            .satisfies(a ->
                assertThat(a.getExpectedDeliveryDate()).as("check expectedDeliveryDate").isEqualTo(expected.getExpectedDeliveryDate())
            )
            .satisfies(a -> assertThat(a.getActualDeliveryDate()).as("check actualDeliveryDate").isEqualTo(expected.getActualDeliveryDate())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getShippingAddress()).as("check shippingAddress").isEqualTo(expected.getShippingAddress()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplyOrderUpdatableRelationshipsEquals(SupplyOrder expected, SupplyOrder actual) {
        assertThat(actual)
            .as("Verify SupplyOrder relationships")
            .satisfies(a -> assertThat(a.getSupplier()).as("check supplier").isEqualTo(expected.getSupplier()));
    }
}
